on:
  push:
    branches:
      - master
  pull_request:

name: "Integration"
jobs:
  chore:
    name: "Testing chores"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: "Use Node.js 10.x"
        uses: actions/setup-node@master
        with:
          version: 10.x

      - name: 'Check that the Yarn files don''t change on new installs (fix w/ "yarn install")'
        run: |
          yarn --immutable --immutable-cache
        env:
          YARN_ENABLE_NETWORK: 0

      - name: "Check that the cache files are consistent with their remote sources"
        run: |
          if [[ $(git diff --name-only "$(git merge-base origin/"$TARGET_BRANCH" HEAD)" HEAD -- .yarn/{cache,virtual} | wc -l) -gt 0 ]]; then
            yarn --immutable --immutable-cache --check-cache
          fi
        if: |
          github.event.pull_request != ''
        env:
          TARGET_BRANCH: ${{github.event.pull_request.base.ref}}

      - name: 'Check that the PR describes which packages should be bumped (fix w/ "yarn version check -i")'
        run: |
          yarn version check
        if: |
          github.event.pull_request != ''
      - name: "Check that the code is formatted"
        run: |
          yarn format:files --chec 

  acceptance:
    strategy:
      fail-fast: false
      matrix:
        node:
          - 8
          - 10
          - 12
        platform:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        exclude:
          - node: 8
            platform: windows-latest

    name: "${{matrix.platform}} w/ Node.js ${{matrix.node}}.x"
    runs-on: ${{matrix.platform}}

    steps:
      - uses: actions/checkout@master

      - name: "Use Node.js ${{matrix.node}}.x"
        uses: actions/setup-node@master
        with:
          version: ${{matrix.node}}.x

      - name: "Build the plugin"
        run: |
          set -e
          yarn build

      - name: "Run the integration tests"
        run: |
          yarn test --runInBand
